# Generated by Django 4.2.4 on 2023-09-25 08:32

import apartment.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_apartment_price'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apartment.models.CustomUserManager()),
            ],
        ),
    ]
