# Generated by Django 4.2.4 on 2023-09-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='number',
            field=models.CharField(max_length=30),
        ),
    ]
